# Build stage
FROM golang:1.21-alpine AS builder
ENV GO111MODULE=auto

WORKDIR /app
COPY ./vioapi ./vioapi
COPY ./viodata ./viodata

WORKDIR /app/vioapi
RUN go mod download

RUN GOOS=linux GOARCH=amd64 go build -o vioapi -tags musl ./cmd/vioapi/main.go

# Final stage
FROM alpine:3.16
RUN apk add --update ca-certificates
COPY --from=builder /app/vioapi/vioapi /usr/bin/vioapi

CMD [ "/usr/bin/vioapi" ]