# Build stage
FROM golang:1.21-alpine AS builder
ENV GO111MODULE=auto

WORKDIR /app
COPY ./data_dump.csv ./data_dump.csv
COPY ./vioapi ./vioapi
COPY ./viodata ./viodata

WORKDIR /app/vioapi
RUN go mod download

RUN GOOS=linux GOARCH=amd64 go build -o importer -tags musl ./cmd/importer/main.go

# Final stage
FROM alpine:3.16
RUN apk add --update ca-certificates
COPY --from=builder /app/vioapi/importer /usr/bin/importer
COPY --from=builder /app/data_dump.csv /app/data_dump.csv
CMD [ "/usr/bin/importer" ]